TABLE PATIENTS
{
	SUBJECT_ID INT [primary key]
	GENDER VARCHAR
	ANCHOR_AGE INT
	ANCHOR_YEAR INT
	ANCHOR_YEAR_GROUP VARCHAR
	DOD TIMESTAMP
}

 TABLE ICUSTAYS
{
	SUBJECT_ID INT
	HADM_ID INT
	STAY_ID INT [primary key]
	FIRST_CAREUNIT VARCHAR
	LAST_CAREUNIT VARCHAR
	INTIME TIMESTAMP
	OUTTIME TIMESTAMP
	LOS DOUBLE
}

TABLE ADMISSIONS
{
	SUBJECT_ID INT
	HADM_ID INT [primary key]
	ADMITTIME TIMESTAMP
	DISCHTIME TIMESTAMP
	DEATHTIME TIMESTAMP
	ADMISSION_TYPE VARCHAR
	ADMISSION_LOCATION VARCHAR
	DISCHARGE_LOCATION VARCHAR
	INSURANCE VARCHAR
	LANGUAGE VARCHAR
	MARITAL_STATUS VARCHAR
	ETHNICITY VARCHAR
	EDREGTIME TIMESTAMP
	EDOUTTIME TIMESTAMP
	HOSPITAL_EXPIRE_FLAG SMALLINT
}

TABLE DIAGNOSES_ICD
{
	SUBJECT_ID INT
	HADM_ID INT
	SEQ_NUM INT
	ICD_CODE VARCHAR
	ICD_VERSION INT
}

TABLE PROCEDURES_ICD
{
	SUBJECT_ID INT
	HADM_ID INT
	SEQ_NUM INT
	CHARTDATE TIMESTAMP
	ICD_CODE VARCHAR
	ICD_VERSION INT
}

TABLE CHARTEVENTS
{
	SUBJECT_ID INT
	HADM_ID INT
	STAY_ID INT
	CHARTTIME TIMESTAMP
	STORETIME TIMESTAMP
	ITEMID INT
	VALUE VARCHAR
	VALUENUM DOUBLE
	VALUEUOM VARCHAR
	WARNING SMALLINT
}

TABLE LABEVENTS
{
	LABEVENT_ID INT [primary key]
	SUBJECT_ID INT
	HADM_ID INT
	SPECIMEN_ID INT
	ITEMID INT
	CHARTTIME TIMESTAMP
	STORETIME TIMESTAMP
	VALUE VARCHAR
	VALUENUM DOUBLE
	VALUEUOM VARCHAR
	REF_RANGE_LOWER DOUBLE
	REF_RANGE_UPPER  DOUBLE
	FLAG VARCHAR
	PRIORITY VARCHAR
	COMMENTS VARCHAR
}

TABLE PRESCRIPTIONS
{
	SUBJECT_ID INT
	HADM_ID INT
	PHARMACY_ID INT
	STARTTIME TIMESTAMP
	STOPTIME TIMESTAMP
	DRUG_TYPE VARCHAR
	DRUG VARCHAR
	GSN VARCHAR
	NDC VARCHAR
	PROD_STRENGTH VARCHAR
	FORM_RX  VARCHAR
	DOSE_VAL_RX VARCHAR
	DOSE_UNIT_RX VARCHAR
	FORM_VAL_DISP VARCHAR
	FORM_UNIT_DISP VARCHAR
	DOSES_PER_24_HRS DOUBLE
	ROUTE VARCHAR(30)
}

TABLE D_ITEMS
{
	ITEMID INT [primary key]
	LABEL VARCHAR
	ABBREVIATION VARCHAR
	LINKSTO VARCHAR
	CATEGORY VARCHAR
	UNITNAME VARCHAR
	PARAM_TYPE VARCHAR
	LOWNORMALVALUE DOUBLE
	HIGHNORMALVALUE DOUBLE
}

TABLE D_LABITEMS
{
	ITEMID INT [primary key]
	LABEL VARCHAR
	FLUID VARCHAR
	CATEGORY VARCHAR
	LOINC_CODE VARCHAR
}

Ref: ICUSTAYS.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: ICUSTAYS.HADM_ID > ADMISSIONS.SUBJECT_ID

Ref: DIAGNOSES_ICD.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: DIAGNOSES_ICD.HADM_ID > ADMISSIONS.HADM_ID

Ref: PROCEDURES_ICD.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: PROCEDURES_ICD.HADM_ID > ADMISSIONS.HADM_ID

Ref: CHARTEVENTS.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: CHARTEVENTS.HADM_ID > ADMISSIONS.HADM_ID
Ref: CHARTEVENTS.STAY_ID > ICUSTAYS.STAY_ID
Ref: CHARTEVENTS.ITEMID > D_ITEMS.ITEMID

Ref: LABEVENTS.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: LABEVENTS.HADM_ID > ADMISSIONS.HADM_ID
Ref: LABEVENTS.ITEMID > D_LABITEMS.ITEMID

Ref: PRESCRIPTIONS.SUBJECT_ID > PATIENTS.SUBJECT_ID
Ref: PRESCRIPTIONS.HADM_ID > ADMISSIONS.HADM_ID