name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f text_requirements.txt ]; then pip install -r text_requirements.txt; fi
    - name: Lint with Pylint
      run: |
         pylint -j 2 data_transformation ml/py_models --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        python -m pytest